service: my-express-app
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DB_URL: ${env:DB_URL}
    PORT: 5000

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any
